/*
 * Copyright (C) 2026 Misha Nasledov <misha@nasledov.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 */

/*
 * tests/proto/test_hope.c — Tier 2 known-answer tests for the
 * src/hope.c module.
 *
 * These tests pin the exact bytes that the HOPE state machine
 * produces from a known (password, session_key, macalg) triple.
 * The point is twofold:
 *
 *   1. Catch any future spec-compliance drift in the password
 *      MAC chain. A change in HMAC ordering, a swapped ikm,
 *      or a renumbered HKDF info string all show up as a
 *      byte-level mismatch here BEFORE any wire round-trip with
 *      a real server. The AEAD interop bug chain from the
 *      claude/hope-chacha20-poly1305 branch (slot swap, HMAC-
 *      chain labeling order, etc.) would have been caught on
 *      the first commit by these vectors instead of after four
 *      rounds of "try, fail against Janus, swap, retry."
 *
 *   2. Lock the spec interpretation into source-controlled form.
 *      fogWraith's HOPE-Secure-Login.md describes the chain as:
 *
 *          password_mac = MAC(key=password, msg=session_key)
 *          encode_key   = MAC(key=password, msg=password_mac)
 *          decode_key   = MAC(key=password, msg=encode_key)
 *
 *      Future readers of src/hope.c shouldn't have to reverse-
 *      engineer "is our encode_key the spec's first-derived or
 *      second-derived?" — the vectors below settle it.
 *
 * Vectors below are generated by feeding the same inputs through
 * GLib's GHmac (or any RFC 2104 / RFC 4231 conformant HMAC) and
 * pasting the result. They are NOT taken from any external
 * specification — they are self-tests pinning OUR implementation
 * against its own past behaviour.
 *
 * To regenerate after a deliberate semantic change: comment out
 * the g_assert_cmpmem lines, run the test, copy the actual bytes
 * from the failure message into the expected[] arrays, restore
 * the assertions. The vectors only need updating when the
 * algorithm itself changes — input + output are both fixed.
 */

#include "config.h"
#include <stdio.h>
#include <string.h>
#include <glib.h>

#include "hope.h"

/* ---------------------------------------------------------------- */
/* Algorithm-list parsing                                            */
/* ---------------------------------------------------------------- */

/* HOPE algo lists are: u16 count (BE) || (u8 namelen || name)+.
 * hope_build_alg_reply emits a 1-entry list; pin the exact bytes. */
static void
test_build_alg_reply_chacha (void)
{
    guint8 buf[64];
    size_t n = hope_build_alg_reply ("CHACHA20-POLY1305", buf, sizeof (buf));

    /* 2 (count) + 1 (namelen) + 17 (name) = 20 bytes */
    g_assert_cmpuint (n, ==, 20);

    /* count = 1, big-endian */
    g_assert_cmpuint (buf[0], ==, 0x00);
    g_assert_cmpuint (buf[1], ==, 0x01);
    /* namelen = 17 */
    g_assert_cmpuint (buf[2], ==, 17);
    /* name */
    g_assert_cmpmem (buf + 3, 17, "CHACHA20-POLY1305", 17);
}

static void
test_build_alg_reply_blowfish (void)
{
    guint8 buf[64];
    size_t n = hope_build_alg_reply ("BLOWFISH", buf, sizeof (buf));
    g_assert_cmpuint (n, ==, 11);
    g_assert_cmpuint (buf[0], ==, 0x00);
    g_assert_cmpuint (buf[1], ==, 0x01);
    g_assert_cmpuint (buf[2], ==, 8);
    g_assert_cmpmem (buf + 3, 8, "BLOWFISH", 8);
}

static void
test_build_alg_reply_empty_returns_zero (void)
{
    guint8 buf[64];
    g_assert_cmpuint (hope_build_alg_reply ("", buf, sizeof (buf)), ==, 0);
    g_assert_cmpuint (hope_build_alg_reply (NULL, buf, sizeof (buf)), ==, 0);
}

static void
test_build_alg_reply_overflow_returns_zero (void)
{
    /* "CHACHA20-POLY1305" needs 20 bytes — give it 19 and confirm
	 * we refuse rather than truncate. */
    guint8 buf[19];
    g_assert_cmpuint (
        hope_build_alg_reply ("CHACHA20-POLY1305", buf, sizeof (buf)), ==, 0);
}

/* ---------------------------------------------------------------- */
/* Cipher name lookups                                               */
/* ---------------------------------------------------------------- */

static void
test_cipher_id_known_names (void)
{
    /* These constants come from cipher.h — we keep them stable on
	 * purpose. If anyone renumbers them, this test will fail
	 * loudly. */
    g_assert_cmpint (hope_cipher_id_from_name ("RC4"),               ==, 1);
    g_assert_cmpint (hope_cipher_id_from_name ("BLOWFISH"),          ==, 2);
    g_assert_cmpint (hope_cipher_id_from_name ("CHACHA20-POLY1305"), ==, 4);
}

static void
test_cipher_id_unknown_returns_none (void)
{
    g_assert_cmpint (hope_cipher_id_from_name (""),         ==, 0);
    g_assert_cmpint (hope_cipher_id_from_name (NULL),       ==, 0);
    g_assert_cmpint (hope_cipher_id_from_name ("AES-256"),  ==, 0);
}

static void
test_cipher_is_aead (void)
{
    g_assert_true  (hope_cipher_is_aead ("CHACHA20-POLY1305"));
    g_assert_false (hope_cipher_is_aead ("BLOWFISH"));
    g_assert_false (hope_cipher_is_aead ("RC4"));
    g_assert_false (hope_cipher_is_aead (""));
    g_assert_false (hope_cipher_is_aead (NULL));
}

/* ---------------------------------------------------------------- */
/* HMAC chain — KNOWN ANSWER TEST                                    */
/* ---------------------------------------------------------------- */

/*
 * Fixed test inputs: a 64-byte session key with a recognisable
 * pattern + a short password + HMAC-SHA256.
 *
 * The session_key embeds 192.168.1.100:5500 in its first 6 bytes
 * (matching what a real HOPE server would emit), followed by 58
 * bytes of low-entropy filler we picked rather than random data
 * so the vectors stay deterministic.
 *
 * Outputs were computed by linking hope.c against this test and
 * dumping the chain bytes the first time — they're the
 * implementation's own behaviour, pinned. The contract this
 * locks down is "calling hope_compute_chain twice on the same
 * inputs produces the same bytes." That's enough to detect
 * accidental input-order swaps, info-string typos, ikm
 * substitutions, etc.
 */
static const guint8 KAT_SESSION_KEY[64] = {
    /* IP 192.168.1.100 + port 5500 (0x157C, BE). */
    0xC0, 0xA8, 0x01, 0x64, 0x15, 0x7C,
    /* Filler — 58 bytes of incrementing pattern. */
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
    0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27,
    0x28, 0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f,
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37,
    0x38, 0x39
};
static const char KAT_PASS[] = "swordfish";

static void
test_chain_hmac_sha256_round_trip (void)
{
    uint8_t pmac1[HOPE_MAC_MAX], ek1[HOPE_MAC_MAX], dk1[HOPE_MAC_MAX];
    uint8_t pmac2[HOPE_MAC_MAX], ek2[HOPE_MAC_MAX], dk2[HOPE_MAC_MAX];

    size_t n1 = hope_compute_chain (KAT_PASS, KAT_SESSION_KEY,
                                    sizeof (KAT_SESSION_KEY),
                                    "HMAC-SHA256", pmac1, ek1, dk1);
    size_t n2 = hope_compute_chain (KAT_PASS, KAT_SESSION_KEY,
                                    sizeof (KAT_SESSION_KEY),
                                    "HMAC-SHA256", pmac2, ek2, dk2);

    /* HMAC-SHA256 is a 256-bit MAC. */
    g_assert_cmpuint (n1, ==, 32);
    g_assert_cmpuint (n2, ==, 32);

    /* Deterministic: same inputs → same outputs. */
    g_assert_cmpmem (pmac1, n1, pmac2, n2);
    g_assert_cmpmem (ek1,   n1, ek2,   n2);
    g_assert_cmpmem (dk1,   n1, dk2,   n2);

    /* The three derived values are distinct from each other.
	 * (HMAC's preimage resistance makes collisions cryptographically
	 * impossible here, but explicit-check belt-and-braces against
	 * a future bug that accidentally aliases the buffers.) */
    g_assert_cmpint (memcmp (pmac1, ek1, n1), !=, 0);
    g_assert_cmpint (memcmp (ek1,   dk1, n1), !=, 0);
    g_assert_cmpint (memcmp (pmac1, dk1, n1), !=, 0);
}

static void
test_chain_hmac_sha1_width (void)
{
    uint8_t pmac[HOPE_MAC_MAX], ek[HOPE_MAC_MAX], dk[HOPE_MAC_MAX];
    size_t n = hope_compute_chain (KAT_PASS, KAT_SESSION_KEY,
                                   sizeof (KAT_SESSION_KEY),
                                   "HMAC-SHA1", pmac, ek, dk);
    /* HMAC-SHA1 = 160-bit = 20 bytes. */
    g_assert_cmpuint (n, ==, 20);
}

static void
test_chain_hmac_md5_width (void)
{
    uint8_t pmac[HOPE_MAC_MAX], ek[HOPE_MAC_MAX], dk[HOPE_MAC_MAX];
    size_t n = hope_compute_chain (KAT_PASS, KAT_SESSION_KEY,
                                   sizeof (KAT_SESSION_KEY),
                                   "HMAC-MD5", pmac, ek, dk);
    /* HMAC-MD5 = 128-bit = 16 bytes. */
    g_assert_cmpuint (n, ==, 16);
}

static void
test_chain_bad_macalg_returns_zero (void)
{
    uint8_t pmac[HOPE_MAC_MAX], ek[HOPE_MAC_MAX], dk[HOPE_MAC_MAX];
    g_assert_cmpuint (hope_compute_chain (KAT_PASS, KAT_SESSION_KEY,
                                          sizeof (KAT_SESSION_KEY),
                                          "HMAC-NOPE", pmac, ek, dk),
                      ==, 0);
    g_assert_cmpuint (hope_compute_chain (KAT_PASS, KAT_SESSION_KEY,
                                          sizeof (KAT_SESSION_KEY),
                                          "", pmac, ek, dk),
                      ==, 0);
}

/*
 * Pin the EXACT byte values for the SHA-256 chain. Locks down the
 * algorithm ordering — if anyone accidentally swaps the ikm in
 * one of the three HMAC calls, or swaps the encode/decode output
 * slot mapping, or renames a parameter such that pass and msg
 * accidentally swap, this fails.
 *
 * The vectors are not externally derived — they're what the
 * current src/hope.c produces. The point is regression
 * detection, not spec conformance (the AEAD Tier 3 tests
 * against Janus cover wire compat).
 */
static void
test_chain_hmac_sha256_known_answer (void)
{
    uint8_t pmac[HOPE_MAC_MAX], ek[HOPE_MAC_MAX], dk[HOPE_MAC_MAX];
    size_t n = hope_compute_chain (KAT_PASS, KAT_SESSION_KEY,
                                   sizeof (KAT_SESSION_KEY),
                                   "HMAC-SHA256", pmac, ek, dk);
    g_assert_cmpuint (n, ==, 32);

    /* password_mac = HMAC-SHA256(key="swordfish", msg=KAT_SESSION_KEY) */
    static const guint8 EXPECTED_PASSWORD_MAC[32] = {
        0xe0, 0x28, 0xcf, 0x9c, 0x75, 0xb2, 0x78, 0x3a,
        0x8a, 0xd9, 0x8a, 0x63, 0xd4, 0x48, 0x29, 0xad,
        0x00, 0xfb, 0x1c, 0x73, 0x93, 0x85, 0x75, 0xd1,
        0xe8, 0x83, 0xf7, 0xbb, 0x23, 0xa9, 0x25, 0x7f
    };
    /* encode_key = HMAC-SHA256(key="swordfish", msg=password_mac) */
    static const guint8 EXPECTED_ENCODE_KEY[32] = {
        0x9e, 0x10, 0xec, 0xed, 0xa0, 0xd7, 0xc3, 0x11,
        0xbc, 0xed, 0x31, 0x70, 0xc1, 0xb2, 0x02, 0x96,
        0x71, 0x82, 0x26, 0x69, 0x88, 0xa9, 0x08, 0x19,
        0x49, 0x65, 0x9e, 0x77, 0x77, 0xa6, 0x7d, 0x6f
    };
    /* decode_key = HMAC-SHA256(key="swordfish", msg=encode_key) */
    static const guint8 EXPECTED_DECODE_KEY[32] = {
        0xb6, 0xb9, 0xf5, 0x06, 0xf5, 0xac, 0xfb, 0xf8,
        0xaf, 0x5d, 0xb8, 0x7a, 0x89, 0xd5, 0x6a, 0x6c,
        0x60, 0x11, 0xc7, 0xe2, 0xf2, 0x52, 0x5b, 0x11,
        0xc2, 0xde, 0x76, 0xb2, 0xe6, 0x8b, 0xe7, 0x8d
    };

    g_assert_cmpmem (pmac, n, EXPECTED_PASSWORD_MAC, 32);
    g_assert_cmpmem (ek,   n, EXPECTED_ENCODE_KEY,   32);
    g_assert_cmpmem (dk,   n, EXPECTED_DECODE_KEY,   32);
}

/* ---------------------------------------------------------------- */
/* LOGIN field encoding                                              */
/* ---------------------------------------------------------------- */

static void
test_login_field_xor_variant (void)
{
    /* secure_login = 0 → hl_code (XOR with 0xff). */
    guint8 buf[32];
    size_t n = hope_build_login_field ("guest",
                                       /*secure_login=*/0,
                                       NULL, 0,
                                       "HMAC-SHA256",
                                       buf, sizeof (buf));
    g_assert_cmpuint (n, ==, 5);

    /* 'g' ^ 0xff = 0x98, 'u' ^ 0xff = 0x8a, ... */
    g_assert_cmpuint (buf[0], ==, (guint8) ('g' ^ 0xff));
    g_assert_cmpuint (buf[1], ==, (guint8) ('u' ^ 0xff));
    g_assert_cmpuint (buf[2], ==, (guint8) ('e' ^ 0xff));
    g_assert_cmpuint (buf[3], ==, (guint8) ('s' ^ 0xff));
    g_assert_cmpuint (buf[4], ==, (guint8) ('t' ^ 0xff));
}

static void
test_login_field_hmac_variant (void)
{
    /* secure_login = 1 → HMAC of the login name with session key. */
    guint8 buf[HOPE_MAC_MAX];
    size_t n = hope_build_login_field ("guest",
                                       /*secure_login=*/1,
                                       KAT_SESSION_KEY,
                                       sizeof (KAT_SESSION_KEY),
                                       "HMAC-SHA256",
                                       buf, sizeof (buf));
    g_assert_cmpuint (n, ==, 32);

    /* Deterministic — pin the exact bytes. */
    static const guint8 EXPECTED[32] = {
        0x40, 0x8e, 0x52, 0xa2, 0xa5, 0x00, 0xe6, 0xf8,
        0xf3, 0x27, 0x6d, 0x9f, 0x8d, 0x75, 0x33, 0xbe,
        0x23, 0xc4, 0x85, 0x3e, 0x0d, 0xb9, 0xc2, 0xee,
        0xff, 0x59, 0x50, 0x00, 0x37, 0x98, 0xbe, 0x2b
    };
    g_assert_cmpmem (buf, n, EXPECTED, 32);
}

/* ---------------------------------------------------------------- */
/* Session-key IP validation                                         */
/* ---------------------------------------------------------------- */

static void
test_sessionkey_ip_match (void)
{
    char warn[256] = { 0 };
    /* KAT key embeds 192.168.1.100:5500. */
    const char *r = hope_validate_sessionkey_ip (
        KAT_SESSION_KEY, sizeof (KAT_SESSION_KEY),
        "192.168.1.100", 5500, warn, sizeof (warn));
    g_assert_null (r);
    /* warn untouched. */
    g_assert_cmpstr (warn, ==, "");
}

static void
test_sessionkey_ip_mismatch_port (void)
{
    char warn[256] = { 0 };
    const char *r = hope_validate_sessionkey_ip (
        KAT_SESSION_KEY, sizeof (KAT_SESSION_KEY),
        "192.168.1.100", /*wrong port*/ 9999,
        warn, sizeof (warn));
    g_assert_nonnull (r);
    /* Returns the same buffer it wrote into. */
    g_assert_true (r == warn);
    /* Warning mentions both IPs/ports. */
    g_assert_nonnull (strstr (warn, "192.168.1.100"));
    g_assert_nonnull (strstr (warn, "5500"));
    g_assert_nonnull (strstr (warn, "9999"));
}

static void
test_sessionkey_ip_mismatch_addr (void)
{
    char warn[256] = { 0 };
    const char *r = hope_validate_sessionkey_ip (
        KAT_SESSION_KEY, sizeof (KAT_SESSION_KEY),
        "10.0.0.1", 5500, warn, sizeof (warn));
    g_assert_nonnull (r);
    g_assert_nonnull (strstr (warn, "10.0.0.1"));
    g_assert_nonnull (strstr (warn, "192.168.1.100"));
}

static void
test_sessionkey_ip_short_key_is_silent (void)
{
    char warn[256] = { 0 };
    /* < 6 bytes — no IP:port prefix to check. */
    const char *r = hope_validate_sessionkey_ip (
        KAT_SESSION_KEY, 4, "10.0.0.1", 5500, warn, sizeof (warn));
    g_assert_null (r);
}

/* ---------------------------------------------------------------- */

int
main (int argc, char **argv)
{
    g_test_init (&argc, &argv, NULL);

    g_test_add_func ("/proto/hope/build_alg_reply/chacha",
                     test_build_alg_reply_chacha);
    g_test_add_func ("/proto/hope/build_alg_reply/blowfish",
                     test_build_alg_reply_blowfish);
    g_test_add_func ("/proto/hope/build_alg_reply/empty",
                     test_build_alg_reply_empty_returns_zero);
    g_test_add_func ("/proto/hope/build_alg_reply/overflow",
                     test_build_alg_reply_overflow_returns_zero);

    g_test_add_func ("/proto/hope/cipher_id/known",
                     test_cipher_id_known_names);
    g_test_add_func ("/proto/hope/cipher_id/unknown",
                     test_cipher_id_unknown_returns_none);
    g_test_add_func ("/proto/hope/cipher_is_aead", test_cipher_is_aead);

    g_test_add_func ("/proto/hope/chain/sha256_round_trip",
                     test_chain_hmac_sha256_round_trip);
    g_test_add_func ("/proto/hope/chain/sha1_width",
                     test_chain_hmac_sha1_width);
    g_test_add_func ("/proto/hope/chain/md5_width", test_chain_hmac_md5_width);
    g_test_add_func ("/proto/hope/chain/bad_macalg",
                     test_chain_bad_macalg_returns_zero);
    g_test_add_func ("/proto/hope/chain/sha256_known_answer",
                     test_chain_hmac_sha256_known_answer);

    g_test_add_func ("/proto/hope/login_field/xor", test_login_field_xor_variant);
    g_test_add_func ("/proto/hope/login_field/hmac",
                     test_login_field_hmac_variant);

    g_test_add_func ("/proto/hope/sessionkey_ip/match",
                     test_sessionkey_ip_match);
    g_test_add_func ("/proto/hope/sessionkey_ip/mismatch_port",
                     test_sessionkey_ip_mismatch_port);
    g_test_add_func ("/proto/hope/sessionkey_ip/mismatch_addr",
                     test_sessionkey_ip_mismatch_addr);
    g_test_add_func ("/proto/hope/sessionkey_ip/short_key",
                     test_sessionkey_ip_short_key_is_silent);

    return g_test_run ();
}
